### ISSUE TITLE
Demo page on mobile 

### ISSUE THREAD

**Issue by HarelM** [lhapaipai/maplibre-theme#1]
The demo page doesn't look good on mobile...
I would advise to use a drop down for mobile to show the different themes.

**Comment by lhapaipai** [comment]
actually the demo page was not very appealing, I replaced it with something more advanced to show the possibilities of the tool. and mobile compatible... Don't hesitate if you have any suggestions or close the issue.
Have a good day.
[demo page](https://maplibre-theme.pentatrion.com/)

**Comment by HarelM** [comment]
Nice! Keep up the good work!
